/* This is an automatically generated file */

#ifndef quirks_H
#ifndef NO_QUIRKS

#define argon2_ctx _rubidium_argon2_ctx
#define argon2_decode_string _rubidium_argon2_decode_string
#define argon2_encode_string _rubidium_argon2_encode_string
#define argon2_fill_memory_blocks _rubidium_argon2_fill_memory_blocks
#define argon2_fill_segment_avx2 _rubidium_argon2_fill_segment_avx2
#define argon2_fill_segment_avx512f _rubidium_argon2_fill_segment_avx512f
#define argon2_fill_segment_ref _rubidium_argon2_fill_segment_ref
#define argon2_fill_segment_ssse3 _rubidium_argon2_fill_segment_ssse3
#define argon2_finalize _rubidium_argon2_finalize
#define argon2_hash _rubidium_argon2_hash
#define argon2_initialize _rubidium_argon2_initialize
#define argon2_validate_inputs _rubidium_argon2_validate_inputs
#define argon2_verify _rubidium_argon2_verify
#define argon2i_hash_encoded _rubidium_argon2i_hash_encoded
#define argon2i_hash_raw _rubidium_argon2i_hash_raw
#define argon2i_verify _rubidium_argon2i_verify
#define argon2id_hash_encoded _rubidium_argon2id_hash_encoded
#define argon2id_hash_raw _rubidium_argon2id_hash_raw
#define argon2id_verify _rubidium_argon2id_verify
#define blake2b _rubidium_blake2b
#define blake2b_compress_avx2 _rubidium_blake2b_compress_avx2
#define blake2b_compress_ref _rubidium_blake2b_compress_ref
#define blake2b_compress_sse41 _rubidium_blake2b_compress_sse41
#define blake2b_compress_ssse3 _rubidium_blake2b_compress_ssse3
#define blake2b_final _rubidium_blake2b_final
#define blake2b_init _rubidium_blake2b_init
#define blake2b_init_key _rubidium_blake2b_init_key
#define blake2b_init_key_salt_personal _rubidium_blake2b_init_key_salt_personal
#define blake2b_init_param _rubidium_blake2b_init_param
#define blake2b_init_salt_personal _rubidium_blake2b_init_salt_personal
#define blake2b_long _rubidium_blake2b_long
#define blake2b_pick_best_implementation _rubidium_blake2b_pick_best_implementation
#define blake2b_salt_personal _rubidium_blake2b_salt_personal
#define blake2b_update _rubidium_blake2b_update
#define core_h2c_string_to_hash _rubidium_core_h2c_string_to_hash
#define escrypt_PBKDF2_SHA256 _rubidium_escrypt_PBKDF2_SHA256
#define escrypt_alloc_region _rubidium_escrypt_alloc_region
#define escrypt_free_local _rubidium_escrypt_free_local
#define escrypt_free_region _rubidium_escrypt_free_region
#define escrypt_gensalt_r _rubidium_escrypt_gensalt_r
#define escrypt_init_local _rubidium_escrypt_init_local
#define escrypt_kdf_nosse _rubidium_escrypt_kdf_nosse
#define escrypt_kdf_sse _rubidium_escrypt_kdf_sse
#define escrypt_parse_setting _rubidium_escrypt_parse_setting
#define escrypt_r _rubidium_escrypt_r
#define fe25519_frombytes _rubidium_fe25519_frombytes
#define fe25519_invert _rubidium_fe25519_invert
#define fe25519_tobytes _rubidium_fe25519_tobytes
#define ge25519_add_cached _rubidium_ge25519_add_cached
#define ge25519_double_scalarmult_vartime _rubidium_ge25519_double_scalarmult_vartime
#define ge25519_from_hash _rubidium_ge25519_from_hash
#define ge25519_from_uniform _rubidium_ge25519_from_uniform
#define ge25519_frombytes _rubidium_ge25519_frombytes
#define ge25519_frombytes_negate_vartime _rubidium_ge25519_frombytes_negate_vartime
#define ge25519_has_small_order _rubidium_ge25519_has_small_order
#define ge25519_is_canonical _rubidium_ge25519_is_canonical
#define ge25519_is_on_curve _rubidium_ge25519_is_on_curve
#define ge25519_is_on_main_subgroup _rubidium_ge25519_is_on_main_subgroup
#define ge25519_p1p1_to_p2 _rubidium_ge25519_p1p1_to_p2
#define ge25519_p1p1_to_p3 _rubidium_ge25519_p1p1_to_p3
#define ge25519_p3_to_cached _rubidium_ge25519_p3_to_cached
#define ge25519_p3_tobytes _rubidium_ge25519_p3_tobytes
#define ge25519_scalarmult _rubidium_ge25519_scalarmult
#define ge25519_scalarmult_base _rubidium_ge25519_scalarmult_base
#define ge25519_sub_cached _rubidium_ge25519_sub_cached
#define ge25519_tobytes _rubidium_ge25519_tobytes
#define ristretto255_from_hash _rubidium_ristretto255_from_hash
#define ristretto255_frombytes _rubidium_ristretto255_frombytes
#define ristretto255_p3_tobytes _rubidium_ristretto255_p3_tobytes
#define sc25519_invert _rubidium_sc25519_invert
#define sc25519_is_canonical _rubidium_sc25519_is_canonical
#define sc25519_mul _rubidium_sc25519_mul
#define sc25519_muladd _rubidium_sc25519_muladd
#define sc25519_reduce _rubidium_sc25519_reduce

#endif
#endif
