/* This is an automatically generated file */

#ifndef quirks_H
#ifndef NO_QUIRKS

#define argon2_ctx _lithium_argon2_ctx
#define argon2_decode_string _lithium_argon2_decode_string
#define argon2_encode_string _lithium_argon2_encode_string
#define argon2_fill_memory_blocks _lithium_argon2_fill_memory_blocks
#define argon2_fill_segment_avx2 _lithium_argon2_fill_segment_avx2
#define argon2_fill_segment_avx512f _lithium_argon2_fill_segment_avx512f
#define argon2_fill_segment_ref _lithium_argon2_fill_segment_ref
#define argon2_fill_segment_ssse3 _lithium_argon2_fill_segment_ssse3
#define argon2_finalize _lithium_argon2_finalize
#define argon2_hash _lithium_argon2_hash
#define argon2_initialize _lithium_argon2_initialize
#define argon2_validate_inputs _lithium_argon2_validate_inputs
#define argon2_verify _lithium_argon2_verify
#define argon2i_hash_encoded _lithium_argon2i_hash_encoded
#define argon2i_hash_raw _lithium_argon2i_hash_raw
#define argon2i_verify _lithium_argon2i_verify
#define argon2id_hash_encoded _lithium_argon2id_hash_encoded
#define argon2id_hash_raw _lithium_argon2id_hash_raw
#define argon2id_verify _lithium_argon2id_verify
#define blake2b _lithium_blake2b
#define blake2b_compress_avx2 _lithium_blake2b_compress_avx2
#define blake2b_compress_ref _lithium_blake2b_compress_ref
#define blake2b_compress_sse41 _lithium_blake2b_compress_sse41
#define blake2b_compress_ssse3 _lithium_blake2b_compress_ssse3
#define blake2b_final _lithium_blake2b_final
#define blake2b_init _lithium_blake2b_init
#define blake2b_init_key _lithium_blake2b_init_key
#define blake2b_init_key_salt_personal _lithium_blake2b_init_key_salt_personal
#define blake2b_init_param _lithium_blake2b_init_param
#define blake2b_init_salt_personal _lithium_blake2b_init_salt_personal
#define blake2b_long _lithium_blake2b_long
#define blake2b_pick_best_implementation _lithium_blake2b_pick_best_implementation
#define blake2b_salt_personal _lithium_blake2b_salt_personal
#define blake2b_update _lithium_blake2b_update
#define core_h2c_string_to_hash _lithium_core_h2c_string_to_hash
#define escrypt_PBKDF2_SHA256 _lithium_escrypt_PBKDF2_SHA256
#define escrypt_alloc_region _lithium_escrypt_alloc_region
#define escrypt_free_local _lithium_escrypt_free_local
#define escrypt_free_region _lithium_escrypt_free_region
#define escrypt_gensalt_r _lithium_escrypt_gensalt_r
#define escrypt_init_local _lithium_escrypt_init_local
#define escrypt_kdf_nosse _lithium_escrypt_kdf_nosse
#define escrypt_kdf_sse _lithium_escrypt_kdf_sse
#define escrypt_parse_setting _lithium_escrypt_parse_setting
#define escrypt_r _lithium_escrypt_r
#define fe25519_frombytes _lithium_fe25519_frombytes
#define fe25519_invert _lithium_fe25519_invert
#define fe25519_tobytes _lithium_fe25519_tobytes
#define ge25519_add_cached _lithium_ge25519_add_cached
#define ge25519_double_scalarmult_vartime _lithium_ge25519_double_scalarmult_vartime
#define ge25519_from_hash _lithium_ge25519_from_hash
#define ge25519_from_uniform _lithium_ge25519_from_uniform
#define ge25519_frombytes _lithium_ge25519_frombytes
#define ge25519_frombytes_negate_vartime _lithium_ge25519_frombytes_negate_vartime
#define ge25519_has_small_order _lithium_ge25519_has_small_order
#define ge25519_is_canonical _lithium_ge25519_is_canonical
#define ge25519_is_on_curve _lithium_ge25519_is_on_curve
#define ge25519_is_on_main_subgroup _lithium_ge25519_is_on_main_subgroup
#define ge25519_p1p1_to_p2 _lithium_ge25519_p1p1_to_p2
#define ge25519_p1p1_to_p3 _lithium_ge25519_p1p1_to_p3
#define ge25519_p3_to_cached _lithium_ge25519_p3_to_cached
#define ge25519_p3_tobytes _lithium_ge25519_p3_tobytes
#define ge25519_scalarmult _lithium_ge25519_scalarmult
#define ge25519_scalarmult_base _lithium_ge25519_scalarmult_base
#define ge25519_sub_cached _lithium_ge25519_sub_cached
#define ge25519_tobytes _lithium_ge25519_tobytes
#define ristretto255_from_hash _lithium_ristretto255_from_hash
#define ristretto255_frombytes _lithium_ristretto255_frombytes
#define ristretto255_p3_tobytes _lithium_ristretto255_p3_tobytes
#define sc25519_invert _lithium_sc25519_invert
#define sc25519_is_canonical _lithium_sc25519_is_canonical
#define sc25519_mul _lithium_sc25519_mul
#define sc25519_muladd _lithium_sc25519_muladd
#define sc25519_reduce _lithium_sc25519_reduce

#endif
#endif
