#ifndef salsa20_xmm6_asm_namespace_H
#define salsa20_xmm6_asm_namespace_H

#define stream_salsa20_xmm6 _lithium_stream_salsa20_xmm6
#define _stream_salsa20_xmm6 __lithium_stream_salsa20_xmm6

#define stream_salsa20_xmm6_xor_ic _lithium_stream_salsa20_xmm6_xor_ic
#define _stream_salsa20_xmm6_xor_ic __lithium_stream_salsa20_xmm6_xor_ic

#endif
