
#ifndef rubidium_H
#define rubidium_H

#include "rubidium/rubidium_aead_aes256gcm.h"
#include "rubidium/rubidium_aead_aegis128l.h"
#include "rubidium/rubidium_aead_aegis256.h"
#include "rubidium/rubidium_aead_chacha20poly1305.h"
#include "rubidium/rubidium_aead_xchacha20poly1305.h"
#include "rubidium/rubidium_auth.h"
#include "rubidium/rubidium_auth_hmacsha256.h"
#include "rubidium/rubidium_auth_hmacsha512.h"
#include "rubidium/rubidium_auth_hmacsha512256.h"
#include "rubidium/rubidium_box_curve25519xsalsa20poly1305.h"
#include "rubidium/rubidium_core_hsalsa20.h"
#include "rubidium/rubidium_core_hchacha20.h"
#include "rubidium/rubidium_core_salsa20.h"
#include "rubidium/rubidium_core_salsa2012.h"
#include "rubidium/rubidium_core_salsa208.h"
#include "rubidium/rubidium_generichash_blake2b.h"
#include "rubidium/rubidium_hash.h"
#include "rubidium/rubidium_hash_sha256.h"
#include "rubidium/rubidium_hash_sha512.h"
#include "rubidium/rubidium_kdf.h"
#include "rubidium/rubidium_kdf_blake2b.h"
#include "rubidium/rubidium_kx.h"
#include "rubidium/rubidium_onetimeauth.h"
#include "rubidium/rubidium_onetimeauth_poly1305.h"
#include "rubidium/rubidium_pwhash.h"
#include "rubidium/rubidium_pwhash_argon2i.h"
#include "rubidium/rubidium_scalarmult.h"
#include "rubidium/rubidium_scalarmult_curve25519.h"
#include "rubidium/rubidium_secretbox.h"
#include "rubidium/rubidium_secretbox_xsalsa20poly1305.h"
#include "rubidium/rubidium_secretstream_xchacha20poly1305.h"
#include "rubidium/rubidium_shorthash.h"
#include "rubidium/rubidium_shorthash_siphash24.h"
#include "rubidium/rubidium_sign.h"
#include "rubidium/rubidium_sign_ed25519.h"
#include "rubidium/rubidium_stream.h"
#include "rubidium/rubidium_stream_chacha20.h"
#include "rubidium/rubidium_stream_salsa20.h"
#include "rubidium/rubidium_stream_xsalsa20.h"
#include "rubidium/rubidium_verify_16.h"
#include "rubidium/rubidium_verify_32.h"
#include "rubidium/rubidium_verify_64.h"
#include "rubidium/randombytes.h"
#include "rubidium/runtime.h"
#include "rubidium/utils.h"
# include "rubidium/rubidium_box_curve25519xchacha20poly1305.h"
# include "rubidium/rubidium_core_ed25519.h"
# include "rubidium/rubidium_core_ristretto255.h"
# include "rubidium/rubidium_kdf_hkdf_sha256.h"
# include "rubidium/rubidium_kdf_hkdf_sha512.h"
# include "rubidium/rubidium_scalarmult_ed25519.h"
# include "rubidium/rubidium_scalarmult_ristretto255.h"
# include "rubidium/rubidium_secretbox_xchacha20poly1305.h"
# include "rubidium/rubidium_pwhash_scryptsalsa208sha256.h"
# include "rubidium/rubidium_stream_salsa2012.h"
# include "rubidium/rubidium_stream_salsa208.h"
# include "rubidium/rubidium_stream_xchacha20.h"

#endif
